from datetime import timedelta

MAX_CHECKIN_DURATION_HOURS = 8
MAX_CHECKIN_DURATION = timedelta(hours=MAX_CHECKIN_DURATION_HOURS)
MAX_CHECKIN_DURATION_MINUTES = MAX_CHECKIN_DURATION_HOURS * 60
XP_PER_CHECKIN_BASE = 50
XP_PER_MINUTE = 2